name: front-end

'on': push

jobs:
  frontend:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: npm fix
      run: |
        npm install --package-lock-only
        npm audit fix --force

    - name: docker-builds
      run: make build


    - name: First builds
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        make docker-build



    
